POST http://localhost:4000/user
Content-Type: application/json

{
    "username": "Myrtle",
    "password": "pw2"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
    "username": "Steve",
    "password": "woof"
}

###

POST http://localhost:4000/blogPosts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN0ZXZlIiwiaWF0IjoxNTg4NjAxMTU1fQ.2y2qCq4IgtzDyhkYGtm_7XNGHHkz3Wphw5FQZZqJ4Hg
Content-Type: application/json

{
    "author_id": 3,
    "title": "School of Rock",
    "post": "underrated film."
}

###

GET http://localhost:4000/blogs
Content-Type: application/json